### ISSUE TITLE
File Picker

### ISSUE THREAD

**Issue by muhamad-ammar** [SalmanFarooqShiekh/ArrangementsFinder#3]
I am thinking to add a file picker through which students can upload their latest placement file. I am just forking and adding this feature.

**Comment by muhamad-ammar** [comment]
@naumansamejo

**Comment by salman-farooq-sh** [comment]
I don't think that's the way to go because uploading the main arrangements file will be a lot of work for the user which the project is trying to reduce in the first place.

This project either needs a solution to automatically fetch the arrangements file on its own or it needs somebody to manually update the arrangements file for every exam.
